### ISSUE TITLE
Activate search input in Races view upon pressing "/"

### ISSUE THREAD

**Issue by toiletgranny** [bibixx/zium.app#10]

**Comment by bibixx** [comment]
@toiletgranny do you think we should indicate somehow that you can actually do that? Something in the search input placeholder maybe? 🤔

**Comment by toiletgranny** [comment]
You're right! Here, I added a [Key indicator component](https://www.figma.com/file/JCMfY8OFGmiDT3lEzSX6zS/Zium.app-Designs?type=design&node-id=833-11862&t=P9KSujJlMfJ5wWhh-4) (it's also used in the [Snackbar component](https://www.figma.com/file/JCMfY8OFGmiDT3lEzSX6zS/Zium.app-Designs?type=design&node-id=833-16569&t=P9KSujJlMfJ5wWhh-4)), and then added a "Shortcut" property in the [Input component](https://www.figma.com/file/JCMfY8OFGmiDT3lEzSX6zS/Zium.app-Designs?type=design&node-id=226-34873&t=P9KSujJlMfJ5wWhh-4).

Here's the end result: https://www.figma.com/file/JCMfY8OFGmiDT3lEzSX6zS/Zium.app-Designs?type=design&node-id=727-28182&t=P9KSujJlMfJ5wWhh-4



![Image](https://github.com/bibixx/zium.app/assets/35307309/12bf4fcd-3261-401d-a8a1-c9c763d51c40)
