### ISSUE TITLE
Incorrect icon for Sprint sessions pre 2023 season

### ISSUE THREAD

**Issue by toiletgranny** [bibixx/zium.app#13]
**As is:** Sprints in race weekends pre 2023 season are marked with an "SQ" icon.
**To be:** "S" icon.

![Image](https://user-images.githubusercontent.com/35307309/247227073-5cb95fa3-fd6f-4582-85df-6ee402c7713e.png)

**Comment by bibixx** [comment]
Of course F1 must mark those as `sprint qualifying` in the API 🤦🏻
