### ISSUE TITLE
"Starts in 0 seconds" in the session date

### ISSUE THREAD

**Issue by toiletgranny** [bibixx/zium.app#14]
**As is:** It seems like the older the race weekend is, the more time it takes to fetch dates of particular events assigned to those weekends. Until the date is loaded, "Starts in 0 seconds" is displayed underneath the session name.
**To be:** Until the sessions' date is loaded, a "Loading..." word should be displayed instead of the "Starts in 0 seconds".

![Image](https://user-images.githubusercontent.com/35307309/247230053-b1c06353-7b26-43ee-9140-0286ef8c2ec9.png)

**Comment by bibixx** [comment]
This seems to be caused by the fact that the individual events in the season 2020 don't have start/end dates. I am going to disable this season for now to fix this
