### ISSUE TITLE
Post-event shows snackbars

### ISSUE THREAD

**Issue by toiletgranny** [bibixx/zium.app#21]

**Comment by toiletgranny** [comment]
Ready to be picked up: https://www.figma.com/file/JCMfY8OFGmiDT3lEzSX6zS/Zium.app-Designs?type=design&node-id=1012-36150&mode=design&t=EvY3907uoahnTgYC-4

Here are a few things to watch out for:
1. In order to enable this use case, the Snackbar component [(Figma link)](https://www.figma.com/file/JCMfY8OFGmiDT3lEzSX6zS/Zium.app-Designs?type=design&node-id=817-9534&mode=design&t=EvY3907uoahnTgYC-4) has undergone a few changes:
   - It now supports displaying two Button components, which should be optional. Note that the padding of the nested Button components has been overridden manually so that they appear a bit smaller.
   - It now supports displaying an image, which should be optional. It should always be `200px` (or `12.5rem`) tall.
   - It now supports disabling the auto-hide, which should be optional. When enabled, the Snackbar component should remain visible until dismissed by the user.
2. There are two types of snackbars:
   - The "Coming up next" snackbar, which should feature the next available show within a given racing weekend. For example, when finished watching Q1, the snackbar should offer to jump into Q2. But when finished watching Q3, the snackbar should offer the pre-qualifying show. 
   - The "Now LIVE" snackbar, which should feature whatever is the currently live broadcasted show. For example, when I'm finished watching a live race and the post-race show begins, the snackbar should offer to jump into that. Or, another example, is when I'm re-watching the quali and the race begins, the snackbar should feature that.

**Comment by bibixx** [comment]
Unfortunately I won't be able to add the `Coming up next` snackbar as from what I can see there is no way for me to get the race weekend id from within a racing event itself 😕
