### ISSUE TITLE
Zero state when there are no more video streams available to be added

### ISSUE THREAD

**Issue by bibixx** [bibixx/zium.app#27]
When there are no more video streams available to be added we currently show no info about it to the user. We should have some kind of a zero state for this situation

![CleanShot 2023-07-16 at 18 31 38@2x](https://github.com/bibixx/zium.app/assets/14880213/c42ec161-8b3e-43cc-9b26-9170f22482f7)

**Comment by bibixx** [comment]
cc @toiletgranny

**Comment by toiletgranny** [comment]
@bibixx How about, instead of showing the empty side sheet, we just disable the "Add video" button when there are no more available streams to be added on your canvas?
