### ISSUE TITLE
Handle non F1 TV Pro users

### ISSUE THREAD

**Issue by bibixx** [bibixx/zium.app#28]
## Case no. 1 — User logged in, no subscription
We shouldn't let users into the app if they have no active subscription. In this case preferably we should point them to the buy subscription page (it'd be also nice to stress that it's not subscription to zium, but to F1 TV)

For now, quickly I have pieced this together:
![CleanShot 2023-07-16 at 23 16 47@2x](https://github.com/bibixx/zium.app/assets/14880213/9f45bd16-d3ab-4c49-95e7-c4ea854bd5bc)

The _Subscribe to F1 TV_ button leads to this page: https://www.formula1.com/subscribe-to-f1-tv
_See global coverage plan_ here: https://www.formula1.com/en/toolbar/content_schedule.html

## Case no. 2 — User logged in, TV Pro Subscription
Probably nothing should in this case

## Case no. 3 — User logged in, TV Access Subscription
I can see 5 places where this affects the app in any way

1. Event Details → "Race" replay/scheduled event paywalled
2. Event Details → "Race" live event paywalled
    * The _TV Access_ grants the user to watch replays but not live events
4. Event Details → "Additional" event paywalled
5. Live event paywalled in the header
    * Currently I just don't show those in the header but maybe we can handle it differently somehow
4. Replay/Scheduled event paywalled in the header (_In case you missed it_ / _Remind me 15 minutes before_)
    * Currently I just don't show those in the header but maybe we can handle it differently somehow. This can be done independently from the live event though.
6. Race View when the user manually enters the url of a paywalled event for them

**Comment by toiletgranny** [comment]
As per our discussion earlier today, we decided to handle inactive subscriptions on the Viewer level. Designs for the information about a lack of proper subscription [can be found here](https://www.figma.com/file/JCMfY8OFGmiDT3lEzSX6zS/Zium.app-Designs?type=design&node-id=1094-13775&mode=design&t=NX4TmZxvA4ju1gla-4).

![image](https://github.com/bibixx/zium.app/assets/35307309/88d2b163-17fb-4dde-90bb-2280bb5db252)

Hint: make sure to enable layout grids in Figma to see the grid used to build the background tiles.
