### ISSUE TITLE
New icon for the F1 Kids Race

### ISSUE THREAD

**Issue by bibixx** [bibixx/zium.app#44]
**Is your feature request related to a problem? Please describe.**
F1 has started creating more and more F1 Kids streams during the race weekends. It'd be nice to have an alternate (maybe more playful?) icon for those events, when opening the event's list

![CleanShot 2024-07-27 at 22 32 26@2x](https://github.com/user-attachments/assets/5962ebf8-ef8e-46f2-b5a1-622e77a1277d)

**Comment by toiletgranny** [comment]
@bibixx Here it is: https://www.figma.com/design/JCMfY8OFGmiDT3lEzSX6zS/Zium.app-Designs?node-id=833-9541&t=ZVYAPBxn3lSsEfzc-4. 

I took the wonky-shaped letters from the F1 Kids logo and rearranged them to fit in a square shape.

![image](https://github.com/user-attachments/assets/c8908b98-42eb-4cf0-92f9-589780dd4488)
